[package]
name = "main_file"
version = "0.1.0"
authors = ["KAKA-OFFICE"]
edition = "2018"
license = "Jass"
description = "Signup Form"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]